version: "3"
services:
    mongo:
        image: mongo
        restart: always
        ports:
          - 27017:27017
        environment:
          - MONGO_INITDB_DATABASE=user
          - MONGO_INITDB_ROOT_USERNAME=root
          - MONGO_INITDB_ROOT_PASSWORD=senha#123
        networks:
          template:
            aliases:
              - mongo
        volumes:
          - '/data/db'
        
    mongo-express:
        image: mongo-express
        container_name: mongo_express
        restart: always
        depends_on:
            - mongo
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=senha#123
        networks:
            template:
                aliases:
                    - mongo-express
    
    app:
        depends_on:
            - mongo
        build: .
        networks:
          template:
            aliases:
              - app
        ports:
            - "8080:8080"
        environment:
            - MONGO_HOST=mongo
            - MONGO_PORT=27017
            - MONGO_USERNAME=root
            - MONGO_PASSWORD=senha#123
            - MONGO_DATABASE=contatos
            - APP_PORT=8080

networks:
    template: {}
